adminapp/urls.py
from django.urls import path
from adminapp import views as admin_views

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', admin_views.UserCreateView.as_view(), name='user_create'),
    path('users/', admin_views.UsersListView.as_view(), name='user_list'),
    path('users/update/<int:pk>/', admin_views.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', admin_views.UserDelete.as_view(), name='user_delete'),

    path('categories/create/', admin_views.CategoryCreate.as_view(), name='category_create'),
    path('categories/', admin_views.CategoryListView.as_view(), name='category_list'),
    path('categories/update/<int:pk>/', admin_views.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', admin_views.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/<int:pk>/', admin_views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', admin_views.ProductsListView.as_view(), name='product_list'),
    path('products/update/<int:pk>/', admin_views.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', admin_views.ProductDeleteView.as_view(), name='product_delete'),
    path('products/detail/<int:pk>/', admin_views.ProductDetail.as_view(), name='product_detail'),
]

authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login', authapp.login, name="login"),
    path('logout', authapp.logout, name="logout"),
    path('register', authapp.register, name="register"),
    path('edit', authapp.edit, name="edit"),
    path('verify/<email>/<key>/', authapp.verify, name="verify"),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name="index"),
    path('', include('social_django.urls', namespace='social')),
    path('contact/', mainapp.contact, name="contact"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('basket/', include('basketapp.urls', namespace="basket")),
    path('auth/', include('authapp.urls', namespace="auth")),
    path('admin/', include('adminapp.urls', namespace="adminapp")),

    path('control/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp

app_name = "mainapp"

urlpatterns = [
    path('', mainapp.ProductsListView.as_view(), name="products"),
    path('category/<int:pk>/', mainapp.ProductsListView.as_view(), name="category"),
    # path('category/<int:pk>/<int:page>/', mainapp.products, name="category_page"),
    path('product/<int:pk>/', mainapp.product, name="product"),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name="название")
    description = models.TextField(verbose_name="описание")
    is_active = models.BooleanField(default=True, verbose_name='активна')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('-id', )

    def delete(self):
        if self.is_active:
            self.is_active = False
        else:
            self.is_active = True
        self.save()


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название')
    image = models.ImageField(upload_to='products', blank=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=255, verbose_name='краткое описание')
    description = models.TextField(verbose_name='описание')
    price = models.DecimalField(decimal_places=2, max_digits=10, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    def delete(self):
        if self.is_active:
            self.is_active = False
        else:
            self.is_active = True
        self.save()

mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.template.loader import render_to_string
from django.views.generic import ListView

from mainapp.models import Product, ProductCategory


def get_hot_product():
    return random.sample(list(Product.objects.all()), 1)[0]


def get_same_products(hot_product):
    products_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return products_list


def index(request):
    context = {
        "title": 'Главная',
        'products': Product.objects.all()[:4],
    }
    return render(request, 'mainapp/index.html', context=context)


def contact(request):
    context = {
        "title": 'Контакты',
    }
    return render(request, 'mainapp/contact.html', context=context)


class ProductsListView(ListView):
    model = Product
    template_name = 'mainapp/products_list.html'
    paginate_by = 2

    def _get_links_menu(self):
        return ProductCategory.objects.filter(is_active=True)

    def get_queryset(self):
        queryset = super().get_queryset()
        category_pk = self.kwargs.get('pk')
        if category_pk and category_pk > 0:
            queryset = queryset.filter(category__pk=category_pk)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_pk = self.kwargs.get('pk')
        context_data['links_menu'] = self._get_links_menu()
        context_data['title'] = "Продукты"

        if category_pk is None:
            hot_product = get_hot_product()
            same_products = get_same_products(hot_product)
            context = {
                'links_menu': self._get_links_menu(),
                "title": "Продукты",
                'hot_product': hot_product,
                'same_products': same_products,
            }
            # rendered_string = render_to_string('mainapp/products.html', context)
            # return HttpResponse(self.request, rendered_string)
        elif category_pk == 0:
            context_data['category'] = {
                'name': 'все',
                'pk': 0,
            }
        else:

            context_data['category'] = ProductCategory.objects.get(pk=category_pk)
        return context_data


def product(request, pk):
    links_menu = ProductCategory.objects.all()
    context = {
        'product': get_object_or_404(Product, pk=pk),
        'links_menu': links_menu

    }

    return render(request, 'mainapp/product.html', context)

mainapp/templates/mainapp/includes/inc_categiries_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:products' %}"
                {% if request.resolver_match.url_name == 'products' %}
           class="active"
                {% endif %}>
            Все
        </a>
    </li>
    {% for link_item in links_menu %}
        <li><a
                href="{% url 'products:category' link_item.pk %}"
                {% if request.resolver_match.kwargs.pk == link_item.pk %} class="active"{% endif %}>
            {{ link_item.name }}
        </a></li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' 0 %}"
                {% if request.resolver_match.url_name == 'products' %}
           class="active"
                {% endif %}>
            Все
        </a>
    </li>
    {% for link_item in links_menu %}
        <li><a
                href="{% url 'products:category' link_item.pk %}"
                {% if request.resolver_match.kwargs.pk == link_item.pk %} class="active"{% endif %}>
            {{ link_item.name }}
        </a></li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'index' %} }}" class="logo"></a>
<ul class="menu">
    <li>
        <a href="{% url 'index' %}"{% if request.resolver_match.url_name == "index" %} class="active"{% endif %}>
            домой
        </a>
    </li>
    <li>
        <a href="{% url 'products:products' %}"{% if request.resolver_match.namespace == 'products' %}
           class="active"{% endif %}>
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}"{% if request.resolver_match.url_name == "contact" %} class="active"{% endif %}>
            контакты
        </a>
    </li>
    {% if user.is_superuser %}
        <li><a href="{% url 'adminapp:user_list' %}">Админка</a></li>
    {% endif %}
    {% if user.is_authenticated %}
        <li><a href="{% url 'auth:edit' %}">{{ user.first_name|default:"Пользователь" }}</a></li>
        <li><a href="{% url 'auth:logout' %}">выйти</a></li>
    {% else %}
        <li><a href="{% url 'auth:register' %}">Регистрация</a></li>
        <li><a href="{% url 'auth:login' %}">войти</a></li>
    {% endif %}
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:basket' %}" class="basket">
    {% if basket %}
        {{ basket.0.total_cost|floatformat:0 }} руб<br>
        {{ basket.0.total_quantity }} шт
    {% endif %}
</a>