authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login', authapp.login, name="login"),
    path('logout', authapp.logout, name="logout"),
    path('register', authapp.register, name="register"),
    path('edit', authapp.edit, name="edit"),
    path('verify/<email>/<key>/', authapp.verify, name="verify"),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name="index"),
    path('', include('social_django.urls', namespace='social')),
    path('contact/', mainapp.contact, name="contact"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('basket/', include('basketapp.urls', namespace="basket")),
    path('auth/', include('authapp.urls', namespace="auth")),
    path('admin/', include('adminapp.urls', namespace="adminapp")),

    path('control/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp

app_name = "mainapp"

urlpatterns = [
    path('', mainapp.ProductsListView.as_view(), name="products"),
    path('category/<int:pk>/', mainapp.ProductsListView.as_view(), name="category"),
    # path('category/<int:pk>/<int:page>/', mainapp.products, name="category_page"),
    path('product/<int:pk>/', mainapp.product, name="product"),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name="название")
    description = models.TextField(verbose_name="описание")
    is_active = models.BooleanField(default=True, verbose_name='активна')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('-id', )

    def delete(self):
        if self.is_active:
            self.is_active = False
        else:
            self.is_active = True
        self.save()


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название')
    image = models.ImageField(upload_to='products', blank=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=255, verbose_name='краткое описание')
    description = models.TextField(verbose_name='описание')
    price = models.DecimalField(decimal_places=2, max_digits=10, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    def delete(self):
        if self.is_active:
            self.is_active = False
        else:
            self.is_active = True
        self.save()

mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.template.loader import render_to_string
from django.views.generic import ListView

from mainapp.models import Product, ProductCategory


def get_hot_product():
    return random.sample(list(Product.objects.all()), 1)[0]


def get_same_products(hot_product):
    products_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return products_list


def index(request):
    context = {
        "title": 'Главная',
        'products': Product.objects.all()[:4],
    }
    return render(request, 'mainapp/index.html', context=context)


def contact(request):
    context = {
        "title": 'Контакты',
    }
    return render(request, 'mainapp/contact.html', context=context)


class ProductsListView(ListView):
    model = Product
    template_name = 'mainapp/products_list.html'
    paginate_by = 2

    def _get_links_menu(self):
        return ProductCategory.objects.filter(is_active=True)

    def get_queryset(self):
        queryset = super().get_queryset()
        category_pk = self.kwargs.get('pk')
        if category_pk and category_pk > 0:
            queryset = queryset.filter(category__pk=category_pk)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_pk = self.kwargs.get('pk')
        context_data['links_menu'] = self._get_links_menu()
        context_data['title'] = "Продукты"

        if category_pk is None:
            hot_product = get_hot_product()
            same_products = get_same_products(hot_product)
            context = {
                'links_menu': self._get_links_menu(),
                "title": "Продукты",
                'hot_product': hot_product,
                'same_products': same_products,
            }
            # rendered_string = render_to_string('mainapp/products.html', context)
            # return HttpResponse(self.request, rendered_string)
        elif category_pk == 0:
            context_data['category'] = {
                'name': 'все',
                'pk': 0,
            }
        else:

            context_data['category'] = ProductCategory.objects.get(pk=category_pk)
        return context_data


def product(request, pk):
    links_menu = ProductCategory.objects.all()
    context = {
        'product': get_object_or_404(Product, pk=pk),
        'links_menu': links_menu

    }

    return render(request, 'mainapp/product.html', context)

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %} {{ title|title }} {% endblock %}</title>
    {% block css %}
        <link rel="stylesheet" href={% static 'style.css' %}>
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="container">
    {% block menu %}
    {% endblock %}

    {% block content %}
    {% endblock %}
    <div class="clr"></div>

</div>

{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
            <p class="small">&copy; VP {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block menu %}
		<div class="hero">
			<div class="header clearfix">
				<a href="/" class="logo"></a>
				<ul class="menu">
                    {% include "mainapp/includes/inc_main_menu.html"%}
				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
			<h1>наши контакты</h1>
		</div>
{% endblock %}
{% block content %}
		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}
{% block menu %}
		<div class="slider">
			<div class="header clearfix">
				<a href="/" class="logo"></a>
				<ul class="menu">
                {% include "mainapp/includes/inc_main_menu.html"%}
				</ul>
				<a href="#" class="search"></a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="/static/img/arrow.png" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>
{% endblock %}
{% block content %}
		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
                {% for product in products %}
				<div class="block">
					<a href="#"><img src="/media/{{ product.image }}" alt="">
						<div class="text">
							<img src="/static/img/icon-hover.png" alt="img">
							<h4>{{ product.name }}</h4>
							<p>{{ product.short_desc}} </p>
						</div> 
					</a>
				</div>
                {% endfor %}
			</div>
		</div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            <a href="/" class="logo"></a>
            <ul class="menu">
                {% include "mainapp/includes/inc_main_menu.html" %}
            </ul>
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="details">
        <div class="links clearfix">
        {% include "mainapp/includes/inc_categiries_menu.html"%}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{% static 'img/slider1.jpg' %}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">Отличный стул</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> 2585.9 <span>руб</span></p>
                <a href="#" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>Расположитесь комфортно.</p>
                    <p>Отличное качество материалов
                        позволит вам это.</p>
                    <p>Различные цвета</p>
                    <p>высочайший уровень
                        эргономики и прочность.</p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}

        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="products_list">
            <div class="title clearfix">
                <h2>
                    Категория: "{{ category.name|title }}"
                </h2>
            </div>
            <div class="pagination">
                {% if page_obj.has_previous %}
                    <a href="{% url 'mainapp:category' category.pk %}?page={{ page_obj.previous_page_number }}"><<</a>
                {% endif %}
                {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                {% if page_obj.has_next %}
                    <a href="{% url 'mainapp:category' category.pk %}?page={{ page_obj.next_page_number }}">>></a>
                {% endif %}
            </div>
            <div class="category-products clearfix">
                {% for product in object_list %}
                    <div class="block">
                        <a href="{% url 'mainapp:product' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="product">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}